name: Security Scan

on:
  push:
    branches: [ main, release-v* ]
  pull_request:
    branches: [ main, release-v* ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    name: Security Scan

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.7.1
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: poetry install --no-interaction

    - name: Run safety scan
      id: security-scan
      run: |
        poetry run safety scan --json --output safety-report.json || true

    - name: Run bandit security linter
      run: |
        poetry run bandit -r app/ -f json -o bandit-report.json || true
        poetry run bandit -r app/

    - name: Check for secrets
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD
        extra_args: --debug --only-verified

    - name: Upload security reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          safety-report.json
          bandit-report.json
